import type { Config } from 'tailwindcss';

// Color + type tokens from the Stitch exports (stitch_medqr_clinic_suite_ui_design/<screen>/code.html),
// which all share one Material-3 palette built on the "Clinical Clarity" teal (#0f766e).
// Ported screens use these names verbatim so markup can be copied across with minimal edits.
const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        // --- Stitch / Material 3 palette ---
        primary: '#005c55',
        'on-primary': '#ffffff',
        'primary-container': '#0f766e',
        'on-primary-container': '#a3faef',
        'primary-fixed': '#9cf2e8',
        'primary-fixed-dim': '#80d5cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        secondary: '#855300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea619',
        'on-secondary-container': '#684000',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        tertiary: '#005f26',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007a33',
        'tertiary-fixed': '#7ffc97',
        'tertiary-fixed-dim': '#62df7d',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005320',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#faf8ff',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#3e4947',
        'inverse-surface': '#283044',
        outline: '#6e7977',
        'outline-variant': '#bdc9c6',

        // --- Older "Clinical Clarity" names still used by not-yet-ported pages ---
        'primary-dark': '#115E59',
        'primary-light': '#CCFBF1',
        'primary-surface': '#F0FDFA',
        'amber-light': '#FEF3C7',
        'amber-dark': '#B45309',
        success: '#16A34A',
        'success-light': '#DCFCE7',
        danger: '#DC2626',
        'danger-light': '#FEE2E2',
        canvas: '#F8FAFC',
        border: '#E2E8F0',
        'text-main': '#0F172A',
        'text-muted': '#64748B',
      },
      spacing: {
        margin: '1rem',
        gutter: '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'display-token': ['Manrope', 'sans-serif'],
        'numeric-metric': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-token': ['56px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'numeric-metric': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-lg': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        xl: '0.75rem',
      },
    },
  },
  plugins: [],
};
export default config;
