import type { Metadata } from 'next';
import { LegalLayout } from '@/components/legal/LegalLayout';
import { CONTACT_EMAIL, CONTACT_PHONE_DISPLAY, CONTACT_PHONE_TEL } from '@/components/support/contactInfo';

export const metadata: Metadata = { title: 'Terms of Use — MedQR' };

const UPDATED = '9 October 2026';

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Use" updated={UPDATED}>
      <p className="font-body-lg text-body-lg text-on-surface">
        MedQR is a registered product and software service owned and operated by <strong>Altis Labs</strong>.
      </p>

      <section>
        <h2>1. Who these terms apply to</h2>
        <p>
          These Terms of Use (&quot;Terms&quot;) govern use of MedQR — the QR-based digital token queue and
          consultation platform available at medqr.in and its clinic subdomains (together, the &quot;Service&quot;).
          They apply to two kinds of users:
        </p>
        <ul>
          <li><strong>Clinics</strong> — the doctors, reception staff and clinic admins who sign up for and operate MedQR at their practice.</li>
          <li><strong>Patients</strong> — anyone who joins a clinic&apos;s digital queue by scanning a QR code or link.</li>
        </ul>
        <p>By creating a clinic account, logging in as staff, or joining a queue as a patient, you agree to these Terms.</p>
      </section>

      <section>
        <h2>2. The Service</h2>
        <p>
          MedQR lets a clinic run a digital, QR-based token queue in place of (or alongside) a physical waiting room, and
          gives doctors a lightweight, free-text place to keep consultation notes and photos of prescriptions or reports.
          MedQR is a queue-management and record-keeping tool — it does not practise medicine, does not give medical advice,
          and is not a substitute for a doctor&apos;s own clinical judgment.
        </p>
      </section>

      <section>
        <h2>3. Clinic accounts</h2>
        <ul>
          <li>A clinic is onboarded by MedQR and receives its own subdomain and staff logins (reception and doctor accounts, and — for clinics with more than one doctor — a clinic admin login).</li>
          <li>Staff passwords are generated by MedQR and must be changed on first login. Keep login credentials confidential; a clinic is responsible for activity under its staff logins.</li>
          <li>A clinic must have the right to collect and share with MedQR any patient information it enters or uploads (see Section 6, Patient data).</li>
        </ul>
      </section>

      <section>
        <h2>4. Fees and payment</h2>
        <ul>
          <li>The base platform is billed monthly at the price shown on the clinic&apos;s Billing page (currently ₹1,199/month + GST for one doctor; ₹499/month + GST per additional doctor). Optional add-on modules are billed separately, also shown on the Billing page.</li>
          <li>WhatsApp notifications to patients are billed from a prepaid wallet, per message, at the rate shown in the app.</li>
          <li>Where MedQR facilitates online (UPI) collection of a clinic&apos;s own consultation fees from patients via a payment gateway, the gateway&apos;s transaction fee and applicable GST are deducted before the remaining amount settles to the clinic&apos;s bank account — this is disclosed in the clinic&apos;s Payments pages.</li>
          <li>Invoices are issued by Altis Labs, the entity operating MedQR.</li>
        </ul>
      </section>

      <section>
        <h2>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for anything unlawful, or to misrepresent a clinic&apos;s identity or qualifications.</li>
          <li>Attempt to access another clinic&apos;s data, or another patient&apos;s records, without authorisation.</li>
          <li>Interfere with the Service&apos;s operation (e.g. scraping, overloading, or probing for vulnerabilities) or circumvent its security.</li>
          <li>Upload content that infringes someone else&apos;s rights or that you don&apos;t have the right to share.</li>
        </ul>
      </section>

      <section>
        <h2>6. Patient data</h2>
        <p>
          Patient information (name, mobile number, age, gender, reason for visit, vitals, and any uploaded prescriptions
          or reports) is entered by the clinic, by reception, or by the patient themselves, and belongs to the clinic as
          the treating provider. MedQR processes it on the clinic&apos;s behalf to run the queue and keep the consultation
          record. See our <a className="text-primary underline" href="/privacy">Privacy Policy</a> for how this data is
          collected, used, and protected.
        </p>
      </section>

      <section>
        <h2>7. Availability and support</h2>
        <p>
          We aim to keep the Service available and reliable, but it is provided on an &quot;as available&quot; basis
          without guaranteeing uninterrupted or error-free operation. Planned maintenance or unplanned outages may
          occasionally affect access. Support requests can be raised from the <a className="text-primary underline" href="/contact">Contact page</a> or, for signed-in clinic staff, from Help &amp; support inside the app.
        </p>
      </section>

      <section>
        <h2>8. Limitation of liability</h2>
        <p>
          MedQR is a queue and record-keeping tool, not a clinical decision-making system. To the maximum extent
          permitted by law, Altis Labs is not liable for clinical decisions made by a doctor, for the accuracy or
          completeness of information a clinic or patient enters, or for indirect or consequential losses arising from
          use of the Service. Nothing in these Terms limits liability that cannot be limited under applicable Indian law.
        </p>
      </section>

      <section>
        <h2>9. Termination</h2>
        <p>
          A clinic may stop using the Service at any time by contacting MedQR support. We may suspend or terminate a
          clinic&apos;s access for a serious or repeated breach of these Terms, non-payment, or fraudulent or unlawful
          use, with notice where practicable. Patient records may be retained after termination as described in the
          Privacy Policy, for as long as required by applicable medical-record and tax retention rules.
        </p>
      </section>

      <section>
        <h2>10. Contact and governing law</h2>
        <p>
          These Terms are governed by the laws of India. Questions about these Terms can be sent to{' '}
          <a className="text-primary underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>, by phone or WhatsApp on{' '}
          <a className="text-primary underline" href={`tel:${CONTACT_PHONE_TEL}`}>{CONTACT_PHONE_DISPLAY}</a>, or through the{' '}
          <a className="text-primary underline" href="/contact">Contact page</a>.
        </p>
        <p className="mt-3 font-body-sm text-body-sm">
          Brand: MedQR · Operated by: Altis Labs · PAN: GRTPK1849H · Udyam Registration No: UDYAM-BR-34-0066884
        </p>
      </section>
    </LegalLayout>
  );
}
